### ISSUE TITLE
Support For Newer Versions

### ISSUE THREAD

**Issue by mlellouch** [smathot/python-eyelinkparser#1] opened 2022-02-06 13:17 UTC
Hey, very useful library!

However it seems it doesn't support newer versions of edf2asc. This is apparent for example in cases like:
`MSG	1031034 start_trial 0`
are now
`MSG	1516000 TRIALID 1`

edit: I'll probably do this myself, so expect a pull request :)

**Comment by smathot** [comment] 2022-02-07 11:07
Glad you find it useful! These messages are not determined by `edf2asc` or by EyeLinkParser, but rather by the experiment software that sends the messages. The `start_trial` message is just the default convention that OpenSesame uses. To override this, you can create a subclass of `EyeLinkParser` and reimplement `is_start_trial()`.

I'm closing this issue, because it's not a bug as such, but feel free to ask questions on the [support forum](https://forum.cogsci.nl/).

**Closed by smathot** 2022-02-07 11:07 UTC

**Comment by mlellouch** [comment] 2022-02-09 11:02
Understood, thanks a lot!
